"""
This code cotains:
    granularities of end-effector movements and their threshold values
    a list of natural language supervisions
"""

import numpy as np
import json

EEF_POS_THRESHOLDS = np.array([-0.15, -0.075, -0.03, 0.0, 0.03, 0.075, 0.15])
EEF_POS_DISCRETE_ACTIONS = np.array([-0.2, -0.1, -0.05, -0.01, 0.01, 0.05, 0.1, 0.2])

EEF_ORI_THRESHOLDS = np.array([-1.1781, -0.5236, -0.1746, 0.0, 0.1746, 0.5236, 1.1781])
EEF_ORI_DISCRETE_ACTIONS = np.array([-1.5708, -0.7854, -0.2618, -0.08727, 0.08727, 0.2618, 0.7854, 1.5708])


NATURAL_LANGUAGE_SUPERVISION = {
    "end_effector": {
        "0_0": [
            "move the arm back by 20 centimeters",
            "retract the arm 20 centimeters",
            "pull the arm back 20 centimeters",
            "shift the arm backward 20 centimeters",
            "draw the arm back by 20 centimeters",
            "move the arm 20 centimeters to the rear",
            "extend the arm back 20 centimeters",
            "push the arm back by 20 centimeters",
            "move the arm 20 centimeters backward",
            "pull the arm backward by 20 centimeters",
            "move the arm back by twenty centimeters",
            "retract the arm twenty centimeters",
            "pull the arm back twenty centimeters",
            "shift the arm backward twenty centimeters",
            "draw the arm back by twenty centimeters",
            "move the arm twenty centimeters to the rear",
            "extend the arm back twenty centimeters",
            "push the arm back by twenty centimeters",
            "move the arm twenty centimeters backward",
            "pull the arm backward by twenty centimeters",
            "move arm backward a lot",
            "move the arm far back",
            "retract the arm significantly",
            "pull the arm back a lot",
            "shift the arm backward a lot",
            "draw the arm back a lot",
            "move the arm back considerably",
            "extend arm far behind in a backward direction",
            "push the arm back a lot",
            "move the arm a good distance backward",
            "pull the arm back substantially",
            "shift the arm far to the rear",
            "move the arm back a lot",
            "pull the arm way back",
            "retract the arm to a great extent",
            "push the arm far to the rear",
            "pull the arm far behind",
            "move the arm a long way back",
            "pull the arm backward by a lot",
            "draw the arm backward deeply",
            "extend the arm backward a lot",
            "shift the arm behind extensively",
            "pull the arm far rearward",
            "move the arm a lot to the back",
            "draw the arm a significant distance back",
            "push the arm backward a lot",
            "move the arm strongly backward",
            "pull the arm backward considerably",
            "move the arm far backward",
            "extend the arm far backward",
            "shift the arm backward a lot"
        ],
        "0_1": [
            "move the arm back by 10 centimeters",
            "retract the arm 10 centimeters",
            "pull the arm back 10 centimeters",
            "shift the arm backward 10 centimeters",
            "draw the arm back by 10 centimeters",
            "move the arm 10 centimeters to the rear",
            "extend the arm back 10 centimeters",
            "push the arm back by 10 centimeters",
            "move the arm 10 centimeters backward",
            "pull the arm backward by 10 centimeters",
            "move the arm back by ten centimeters",
            "retract the arm ten centimeters",
            "pull the arm back ten centimeters",
            "shift the arm backward ten centimeters",
            "draw the arm back by ten centimeters",
            "move the arm ten centimeters to the rear",
            "extend the arm back ten centimeters",
            "push the arm back by ten centimeters",
            "move the arm ten centimeters backward",
            "pull the arm backward by ten centimeters",
            "move arm backward",
            "move the arm back",
            "retract the arm",
            "pull the arm back",
            "shift the arm backward",
            "draw the arm back",
            "move the arm back",
            "extend the arm back",
            "push the arm back",
            "move the arm backward",
            "pull the arm back ",
            "shift the arm to the rear",
            "retract the arm backward",
            "pull the arm backward",
            "shift the arm back",
            "pull the arm back",
            "move the arm rearward",
            "draw the arm backward",
            "push the arm backward",
            "shift the arm rearward",
        ],
        "0_2": [
            "move the arm back by 5 centimeters",
            "retract the arm 5 centimeters",
            "pull the arm back 5 centimeters",
            "shift the arm backward 5 centimeters",
            "draw the arm back by 5 centimeters",
            "move the arm 5 centimeters to the rear",
            "extend the arm back 5 centimeters",
            "push the arm back by 5 centimeters",
            "move the arm 5 centimeters backward",
            "pull the arm backward by 5 centimeters",
            "move the arm back by five centimeters",
            "retract the arm five centimeters",
            "pull the arm back five centimeters",
            "shift the arm backward five centimeters",
            "draw the arm back by five centimeters",
            "move the arm five centimeters to the rear",
            "extend the arm back five centimeters",
            "push the arm back by five centimeters",
            "move the arm five centimeters backward",
            "pull the arm backward by five centimeters",
            "move arm backward a bit",
            "move arm backward slightly",
            "move arm backward by a small amount",
            "move arm backward by a small distance",
            "move the arm backward a bit",
            "move the arm back a bit",
            "retract the arm a bit",
            "pull the arm back slightly",
            "shift the arm backward a bit",
            "draw the arm back a small distance",
            "move the arm back a little",
            "extend the arm back a bit",
            "push the arm back slightly",
            "move the arm a small distance backward",
            "pull the arm back a short distance",
            "shift the arm a little to the rear",
            "pull the arm back by a small amount",
            "move the arm back just a bit",
            "push the arm back by a small distance",
            "draw the arm back slightly",
            "pull the arm backward a bit",
            "shift the arm back by a small margin",
            "move the arm slightly rearward",
            "retract the arm by a small amount",
            "draw the arm back a bit",
            "push the arm back slightly backward",
            "shift the arm back a little",
            "pull the arm back in a small way",
            "retract the arm just a bit",
            "shift the arm back by a small movement",
            "pull the arm back by a slight distance",
            "move the arm backward a little"
        ],
        "0_3": [
            "move the arm back by 1 centimeter",
            "retract the arm 1 centimeter",
            "pull the arm back 1 centimeter",
            "shift the arm backward 1 centimeter",
            "draw the arm back by 1 centimeter",
            "move the arm 1 centimeter to the rear",
            "extend the arm back 1 centimeter",
            "push the arm back by 1 centimeter",
            "move the arm 1 centimeter backward",
            "pull the arm backward by 1 centimeter",
            "move the arm back by one centimeter",
            "retract the arm one centimeter",
            "pull the arm back one centimeter",
            "shift the arm backward one centimeter",
            "draw the arm back by one centimeter",
            "move the arm one centimeter to the rear",
            "extend the arm back one centimeter",
            "push the arm back by one centimeter",
            "move the arm one centimeter backward",
            "pull the arm backward by one centimeter",
            "move arm backward a tiny bit",
            "move the arm back a tiny bit",
            "retract the arm a tiny bit",
            "pull the arm back a tiny amount",
            "shift the arm backward a tiny bit",
            "draw the arm back a tiny bit",
            "extend the arm back a tiny amount",
            "push the arm back a tiny bit",
            "move the arm a very small distance backward",
            "pull the arm back by a tiny amount",
            "shift the arm a very small amount to the rear",
            "move the arm back with a minuscule amount",
            "pull the arm back a minuscule amount",
            "move the arm back just a tiny bit",
            "push the arm back by a minuscule distance",
            "shift the arm back by a tiny margin",
            "pull the arm back by the slightest amount",
            "move the arm barely backward",
            "retract the arm by a very small amount",
            "draw the arm back ever so gently",
            "push the arm back by a tiny fraction",
            "shift the arm back a very small distance",
            "pull the arm back a minuscule distance",
            "retract the arm just a hair",
            "pull the arm back the slightest bit",
            "move the arm back in the tiniest amount",
            "shift the arm back a hair",
            "pull the arm back the barest amount",
            "move the arm backward by the smallest degree"
        ],
        "0_4": [
            "move the arm forward by 1 centimeter",
            "advance the arm 1 centimeter",
            "push the arm forward 1 centimeter",
            "shift the arm forward 1 centimeter",
            "move the arm 1 centimeter ahead",
            "extend the arm forward 1 centimeter",
            "move the arm forward by one centimeter",
            "advance the arm one centimeter",
            "push the arm forward one centimeter",
            "shift the arm forward one centimeter",
            "move the arm one centimeter ahead",
            "extend the arm forward one centimeter",
            "move arm forward a tiny bit",
            "move forward a tiny bit",
            "move the arm forward by a tiny bit",
            "advance the arm a tiny bit",
            "push the arm forward a minuscule amount",
            "shift the arm forward a tiny bit",
            "move the arm forward a very little",
            "extend the arm forward a tiny amount",
            "push the arm forward by a tiny bit",
            "move the arm a very small distance forward",
            "advance the arm by a tiny amount",
            "move the arm forward with a minuscule amount",
            "push the arm forward a minuscule amount",
            "move the arm forward just a tiny bit",
            "advance the arm by a minuscule distance",
            "move the arm forward ever very slightly",
            "push the arm forward with minimal amount",
            "shift the arm forward by a tiny margin",
            "move the arm forward by the slightest amount",
            "move the arm barely forward",
            "advance the arm by a very small amount",
            "shift the arm forward a very small distance",
            "move the arm forward a minuscule distance",
            "push the arm forward just a hair",
            "move the arm forward the slightest bit",
            "move the arm forward in the tiniest amount",
            "shift the arm forward a hair",
            "move the arm forward by the barest amount",
            "advance the arm forward by the smallest degree"
        ],
        "0_5": [
            "move the arm forward by 5 centimeters",
            "advance the arm 5 centimeters",
            "push the arm forward 5 centimeters",
            "shift the arm forward 5 centimeters",
            "move the arm 5 centimeters ahead",
            "extend the arm forward 5 centimeters",
            "move the arm forward by five centimeters",
            "advance the arm five centimeters",
            "push the arm forward five centimeters",
            "shift the arm forward five centimeters",
            "move the arm five centimeters ahead",
            "extend the arm forward five centimeters",
            "move arm forward a bit",
            "move arm forward slightly",
            "move forward a bit",
            "move the arm forward a bit",
            "advance the arm a bit",
            "push the arm forward",
            "push the arm forward slightly",
            "shift the arm forward a bit",
            "move the arm forward a small distance",
            "extend the arm forward a bit",
            "push the arm forward a little",
            "move the arm a small distance forward",
            "advance the arm forward a short distance",
            "shift the arm a little forward",
            "move the arm forward with a slight amount",
            "push the arm forward a small amount",
            "move the arm forward just a bit",
            "advance the arm forward a small distance",
            "shift the arm forward by a small margin",
            "push the arm forward a short distance",
            "advance the arm forward a small amount",
            "extend the arm forward by a small amount",
            "move the arm forward a little further",
            "shift the arm forward a short way",
            "push the arm forward a little bit",
            "advance the arm a short distance forward",
            "move the arm forward slightly",
            "move arm forward slightly"
        ],
        "0_6": [
            "move the arm forward by 10 centimeters",
            "advance the arm 10 centimeters",
            "push the arm forward 10 centimeters",
            "shift the arm forward 10 centimeters",
            "move the arm 10 centimeters ahead",
            "extend the arm forward 10 centimeters",
            "move arm forward 10 centimeters",
            "move the arm forward by ten centimeters",
            "advance the arm ten centimeters",
            "push the arm forward ten centimeters",
            "shift the arm forward ten centimeters",
            "move the arm ten centimeters ahead",
            "extend the arm forward ten centimeters",
            "move arm forward ten centimeters",
            "move the arm forward",
            "move the arm in a forward direction",
            "move forward",
            "advance the arm forward",
            "advance the arm in a forward direction",
            "push the arm forward",
            "shift the arm forward",
            "move the arm ahead",
            "extend the arm forward",
            "move the arm forward to the front",
            "advance the arm to the front",
            "push the arm ahead",
            "shift the arm forward directly",
            "shift arm in a forward direction",
            "move the arm forward ahead",
            "extend the arm forward",
            "move the arm forward to the front",
            "advance the arm forward directly",
            "shift the arm forward directly",
            "move the arm forward in front",
            "push the arm forward in front",
            "shift the arm forward straight",
            "extend the arm straight ahead",
        ],
        "0_7": [
            "move the arm forward by 20 centimeters",
            "advance the arm 20 centimeters",
            "push the arm forward 20 centimeters",
            "shift the arm forward 20 centimeters",
            "move the arm 20 centimeters ahead",
            "extend the arm forward 20 centimeters",
            "move the arm forward by twenty centimeters",
            "advance the arm twenty centimeters",
            "push the arm forward twenty centimeters",
            "shift the arm forward twenty centimeters",
            "move the arm twenty centimeters ahead",
            "extend the arm forward twenty centimeters",
            "move arm forward a lot",
            "move arm a lot in a forward direction",
            "push the arm forward a lot",
            "move the arm forward a lot",
            "advance the arm a great deal",
            "push the arm forward significantly",
            "shift the arm forward a lot",
            "move the arm forward extensively",
            "extend the arm forward a great deal",
            "push the arm far forward",
            "move the arm forward by a large amount",
            "advance the arm forward a lot",
            "shift the arm forward considerably",
            "move the arm forward with a large amount",
            "extend the arm forward substantially",
            "push the arm forward with a great range",
            "move the arm far ahead",
            "advance the arm forward by a large distance",
            "shift the arm far forward",
            "move the arm forward by a considerable amount",
            "extend the arm far forward",
            "extend the arm forward a lot",
            "push the arm forward by a significant distance",
            "move the arm forward a considerable distance",
            "advance the arm forward extensively",
            "shift the arm forward by a large amount",
            "move the arm forward a long way",
            "extend the arm forward a considerable distance"
        ],
        "1_0": [
            "move the arm to the right by 20 centimeters",
            "shift the arm 20 centimeters to the right",
            "extend the arm to the right by 20 centimeters",
            "push the arm 20 centimeters to the right",
            "move the arm to the right by twenty centimeters",
            "shift the arm twenty centimeters to the right",
            "extend the arm to the right by twenty centimeters",
            "push the arm twenty centimeters to the right",
            "move arm to the right a lot",
            "move arm right a lot",
            "move right a lot",
            "move a lot to the right",
            "move the arm far to the right",
            "shift the arm a lot to the right",
            "shift a lot to the right",
            "shift the arm to the right a lot",
            "move the arm a great deal to the right",
            "extend the arm significantly to the right",
            "push the arm far to the right",
            "move the arm to the right extensively",
            "shift the arm considerably to the right",
            "extend the arm far to the right",
            "slide the arm to the right a lot",
            "push the arm to the right a great distance",
            "move the arm to the right by a large amount",
            "shift the arm to the right by a significant amount",
            "move the arm to the right a considerable distance",
            "extend the arm to the right substantially",
            "push the arm to the right significantly",
            "shift the arm far to the right",
            "move the arm to the right with a large amount",
            "extend the arm a long way to the right",
            "push the arm a large distance to the right",
            "move the arm far over to the right",
            "shift the arm to the right by a considerable distance",
            "move the arm to the right a great deal",
            "extend the arm far over to the right",
            "push the arm to the right extensively"
        ],
        "1_1": [    
            "move the arm to the right by 10 centimeters",
            "shift the arm 10 centimeters to the right",
            "extend the arm to the right by 10 centimeters",
            "push the arm 10 centimeters to the right",
            "move the arm to the right by ten centimeters",
            "shift the arm ten centimeters to the right",
            "extend the arm to the right by ten centimeters",
            "push the arm ten centimeters to the right",
            "move arm to the right",
            "move to the right",
            "move right",
            "slide the arm to the right",
            "move the arm to the right",
            "shift the arm to the right",
            "extend the arm to the right",
            "push the arm to the right",
            "move the arm directly to the right",
            "shift the arm directly to the right",
            "shift the arm to the right",
            "move the arm straight to the right",
            "extend the arm straight to the right",
            "move the arm to the right ahead",
            "move the arm forward to the right",
            "extend the arm forward to the right"
        ],
        "1_2": [
            "move the arm to the right by 5 centimeters",
            "shift the arm 5 centimeters to the right",
            "extend the arm to the right by 5 centimeters",
            "push the arm 5 centimeters to the right",
            "move the arm to the right by five centimeters",
            "shift the arm five centimeters to the right",
            "extend the arm to the right by five centimeters",
            "push the arm five centimeters to the right",
            "move arm to the right a bit",
            "move right a bit",
            "move slightly right",
            "move arm right a bit",
            "move the arm to the right a bit",
            "shift the arm a bit to the right",
            "move the arm a little to the right",
            "extend the arm to the right a bit",
            "slide the arm to the right a bit",
            "slide arm slightly to the right",
            "slide the arm a bit to the right",
            "push the arm a bit to the right",
            "shift the arm to the right a small amount",
            "move the arm to the right a little",
            "extend the arm a little to the right",
            "push the arm slightly to the right",
            "move the arm to the right just a bit",
            "shift the arm a little to the right",
            "move the arm a small distance to the right",
            "extend the arm slightly to the right",
            "push the arm to the right a small amount",
            "move the arm to the right a short distance",
            "shift the arm to the right just a little",
            "move the arm to the right by a small margin",
            "extend the arm to the right a short distance",
            "push the arm to the right by a little bit"
        ],
        "1_3": [
            "move the arm to the right by 1 centimeter",
            "shift the arm 1 centimeter to the right",
            "extend the arm to the right by 1 centimeter",
            "push the arm 1 centimeter to the right",
            "move the arm to the right by one centimeter",
            "shift the arm one centimeter to the right",
            "extend the arm to the right by one centimeter",
            "push the arm one centimeter to the right",
            "move arm to the right a tiny bit",
            "move the arm to the right a tiny bit",
            "shift the arm a tiny bit to the right",
            "move the arm just a tiny bit to the right",
            "slide arm a tiny bit to the right",
            "extend the arm to the right a tiny bit",
            "push the arm a tiny bit to the right",
            "move to the right with a minuscule amount",
            "move to the right with a very small amount",
            "move to the right with a tiny amount",
            "move the arm to the right with a minuscule amount",
            "move the arm to the right with a very small amount",
            "move the arm to the right with a tiny amount",
            "shift the arm to the right just a tiny bit",
            "move the arm a minuscule amount to the right",
            "extend the arm a tiny bit to the right",
            "push the arm very slightly to the right",
            "move the arm to the right ever so slightly",
            "push the arm a minuscule distance to the right",
            "move the arm to the right by a tiny amount",
            "shift the arm to the right a hair",
            "move the arm a hair to the right",
            "extend the arm to the right just a tiny bit",
            "push the arm to the right by the smallest margin"
        ],
        "1_4": [
            "move arm to the left a tiny bit", 
            "move the arm to the left by 1 centimeter",
            "shift the arm 1 centimeter to the left",
            "extend the arm to the left by 1 centimeter",
            "push the arm 1 centimeter to the left",
            "move the arm to the left by one centimeter",
            "shift the arm one centimeter to the left",
            "extend the arm to the left by one centimeter",
            "push the arm one centimeter to the left",
            "move the arm to the left a tiny bit",
            "move to the left a tiny bit",
            "shift the arm a tiny bit to the left",
            "slide arm a tiny bit to the left",
            "move the arm just a tiny bit to the left",
            "extend the arm to the left a tiny bit",
            "push the arm a tiny bit to the left",
            "shift the arm to the left just a tiny bit",
            "move the arm a minuscule amount to the left",
            "move to the left with a minuscule amount",
            "move to the left with a very small amount",
            "move to the left with a tiny amount",
            "move the arm to the left with a minuscule amount",
            "move the arm to the left with a very small amount",
            "move the arm to the left with a tiny amount",
            "extend the arm a tiny bit to the left",
            "push the arm very slightly to the left",
            "move the arm to the left ever so slightly",
            "push the arm a minuscule distance to the left",
            "move the arm to the left by a tiny amount",
            "shift the arm to the left a hair",
            "move the arm a hair to the left",
            "extend the arm to the left just a tiny bit",
            "push the arm to the left by the smallest margin"
        ],
        "1_5": [
            "move the arm to the left by 5 centimeters",
            "shift the arm 5 centimeters to the left",
            "move the arm 5 centimeters to the side",
            "extend the arm to the left by 5 centimeters",
            "push the arm 5 centimeters to the left",
            "move the arm to the left by five centimeters",
            "shift the arm five centimeters to the left",
            "move the arm five centimeters to the side",
            "extend the arm to the left by five centimeters",
            "push the arm five centimeters to the left",
            "slide arm slightly to the left",
            "move arm to the left a bit",
            "move arm to the left slightly",
            "move left slightly",
            "move to the left a bit",
            "move the arm to the left a bit",
            "shift the arm a bit to the left",
            "move the arm a little to the left",
            "extend the arm to the left a bit",
            "push the arm a bit to the left",
            "move the arm to the side a bit",
            "shift the arm to the left a small amount",
            "move the arm to the left a little",
            "extend the arm a little to the left",
            "push the arm slightly to the left",
            "move the arm to the left just a bit",
            "shift the arm a little to the left",
            "move the arm a small distance to the left",
            "extend the arm slightly to the left",
            "slide the arm to the left a bit",
            "push the arm to the left a small amount",
            "move the arm to the left a short distance",
            "shift the arm to the left just a little",
            "move the arm to the left by a small margin",
            "extend the arm to the left a short distance",
            "push the arm to the left by a little bit"
        ],
        "1_6": [
            "move the arm to the left by 10 centimeters",
            "shift the arm 10 centimeters to the left",
            "extend the arm to the left by 10 centimeters",
            "push the arm 10 centimeters to the left",
            "move the arm to the left by ten centimeters",
            "shift the arm ten centimeters to the left",
            "extend the arm to the left by ten centimeters",
            "push the arm ten centimeters to the left",
            "move arm to the left",
            "move left",
            "move to the left",
            "move the arm to the left",
            "slide the arm to the left",
            "shift arm to the left",
            "move the arm to the left side",
            "extend the arm to the left",
            "push the arm to the left",
            "move the arm directly to the left",
            "shift the arm directly to the left",
            "extend the arm to the left side",
            "push the arm to the left steadily",
            "shift the arm to the left steadily",
            "move the arm straight to the left",
            "extend the arm straight to the left",
            "push the arm to the left side",
            "move the arm to the left ahead",
            "shift the arm to the left",
        ],
        "1_7": [
            "move the arm to the left by 20 centimeters",
            "shift the arm 20 centimeters to the left",
            "move the arm 20 centimeters to the left side",
            "extend the arm to the left by 20 centimeters",
            "push the arm 20 centimeters to the left",
            "move the arm to the left by twenty centimeters",
            "shift the arm twenty centimeters to the left",
            "move the arm twenty centimeters to the left side",
            "extend the arm to the left by twenty centimeters",
            "push the arm twenty centimeters to the left",
            "move arm to the left a lot",
            "move to the left a lot",
            "move left a lot",
            "slide the arm to the left a lot",
            "slide arm a lot to the left",
            "move the arm to the left a lot",
            "shift the arm a lot to the left",
            "move the arm a great deal to the left",
            "extend the arm significantly to the left",
            "push the arm far to the left",
            "move the arm to the left side extensively",
            "shift the arm considerably to the left",
            "move the arm to the left by a large amount",
            "extend the arm to the left a great deal",
            "push the arm a large distance to the left",
            "move the arm to the left substantially",
            "shift the arm far to the left",
            "move the arm to the left a great distance",
            "extend the arm far to the left",
            "push the arm to the left by a considerable distance",
            "move the arm to the left extensively",
            "shift the arm to the left by a large margin",
            "move the arm far to the left",
            "extend the arm to the left by a significant amount",
            "push the arm to the left a long way"
        ],
        "2_0": [
            "lower the arm by 20 centimeters",
            "move the arm down by 20 centimeters",
            "drop the arm 20 centimeters",
            "lower the arm by twenty centimeters",
            "move the arm down by twenty centimeters",
            "drop the arm twenty centimeters",
            "lower arm a lot",
            "lower the arm a lot",
            "move the arm down a lot",
            "move down a lot",
            "drop the arm significantly",
            "lower the arm considerably",
            "move the arm downward a great deal",
            "drop the arm a large distance",
            "lower the arm substantially",
            "move the arm down extensively",
            "lower the arm far downward",
            "drop the arm by a large amount",
            "lower the arm a great deal",
            "move the arm down by a considerable amount",
            "drop the arm far down",
            "lower the arm to a great extent",
            "move the arm far down",
            "drop the arm extensively",
            "lower the arm down a long way"
        ],
        "2_1": [    
            "lower the arm by 10 centimeters",
            "move the arm down by 10 centimeters",
            "drop the arm 10 centimeters",
            "lower the arm by ten centimeters",
            "move the arm down by ten centimeters",
            "drop the arm ten centimeters",
            "lower arm",
            "lower the arm",
            "lower arm down",
            "move the arm down",
            "move down",
            "move arm down",
            "move downward",
            "drop the arm",
            "move the arm downward",
            "move the arm downwards",
            "bring the arm down",
            "lower the arm to a lower position",
            "drop the arm to a lower position",
            "move the arm straight down",
            "drop the arm straight down",
            "move the arm down steadily",
            "drop the arm to a lower level",
            "bring the arm downward",
            "lower the arm downward"
        ],
        "2_2": [    
            "lower the arm by 5 centimeters",
            "move the arm down by 5 centimeters",
            "drop the arm 5 centimeters",
            "lower the arm by five centimeters",
            "move the arm down by five centimeters",
            "drop the arm five centimeters",
            "lower arm a bit",
            "move arm down a bit",
            "lower the arm a bit",
            "move the arm down a bit",
            "drop the arm a bit",
            "drop the arm slightly",
            "lower the arm slightly",
            "move the arm downward a little",
            "drop the arm a small distance",
            "lower the arm by a small amount",
            "move the arm down a little",
            "drop the arm a bit lower",
            "lower the arm a short distance",
            "move the arm slightly downward",
            "drop the arm just a bit",
            "lower the arm a small way",
            "move the arm down by a small margin",
            "move the arm down by a small amount",
            "drop the arm gently downward",
            "lower the arm by a little",
            "move the arm down just a bit",
            "bring the arm downward a bit",
            "bring the arm down slightly"
        ],
        "2_3": [    
            "lower the arm by 1 centimeter",
            "move the arm down by 1 centimeter",
            "drop the arm 1 centimeter",
            "lower the arm by one centimeter",
            "move the arm down by one centimeter",
            "drop the arm one centimeter",
            "lower arm a tiny bit",
            "lower the arm a tiny bit",
            "move the arm down a tiny bit",
            "move arm down a tiny bit",
            "drop the arm a tiny bit",
            "lower the arm just a tiny bit",
            "move the arm downward a tiny amount",
            "drop the arm a minuscule distance",
            "lower the arm by a tiny amount",
            "lower the arm by a very small amount",
            "move the arm down a hair",
            "drop the arm a hair",
            "lower the arm very slightly",
            "move the arm down just a little",
            "drop the arm just a tiny bit lower",
            "drop the arm ever so slightly",
            "lower the arm by the smallest margin",
            "move the arm down the slightest bit"
        ],
        "2_4": [
            "raise the arm up by 1 centimeter",
            "lift the arm 1 centimeter upward",
            "move the arm up by 1 centimeter",
            "raise the arm up by one centimeter",
            "lift the arm one centimeter upward",
            "move the arm up by one centimeter",
            "raise arm up a tiny bit",
            "raise the arm up a tiny bit",
            "lift the arm up a tiny bit",
            "move the arm upward a tiny bit",
            "raise the arm just a tiny bit",
            "lift the arm a minuscule amount",
            "lift the arm a very small amount",
            "move the arm up a very small amount",
            "raise the arm a tiny amount",
            "lift the arm up just a tiny bit",
            "move the arm up a minuscule distance",
            "lift the arm up ever so slightly",
            "move the arm up just a hair",
            "raise the arm by a hair",
            "lift the arm by the smallest margin",
            "move the arm upward just a tiny bit",
            "raise the arm up very slightly",
            "lift the arm up the slightest bit"
        ],
        "2_5": [    
            "raise the arm up by 5 centimeters",
            "lift the arm 5 centimeters upward",
            "move the arm up by 5 centimeters",
            "raise the arm up by five centimeters",
            "lift the arm five centimeters upward",
            "move the arm up by five centimeters",
            "raise arm up a bit",
            "raise the arm up a bit",
            "lift the arm up a bit",
            "move the arm upward a bit",
            "raise the arm just a bit",
            "lift the arm up slightly",
            "move the arm up a little",
            "raise the arm a small amount",
            "lift the arm up a small distance",
            "move the arm upward just a bit",
            "raise the arm up a little",
            "lift the arm up a small way",
            "move the arm up a short distance",
            "raise the arm up a bit higher",
            "lift the arm by a small margin",
            "move the arm upward by a small amount",
            "raise the arm up a small distance",
            "lift the arm up a slight amount"
        ],
        "2_6": [
            "raise the arm up by 10 centimeters",
            "lift the arm 10 centimeters upward",
            "move the arm up by 10 centimeters",
            "raise the arm up by ten centimeters",
            "lift the arm ten centimeters upward",
            "move the arm up by ten centimeters",
            "raise arm up",
            "raise the arm up",
            "lift the arm up",
            "move the arm upward",
            "raise the arm",
            "lift the arm",
            "move the arm up",
            "raise the arm to a higher position",
            "lift the arm to a higher level",
            "move the arm straight up",
            "raise the arm upward",
            "lift the arm upward",
            "raise the arm directly up",
            "lift the arm up directly",
        ],
        "2_7": [
            "raise the arm up by 20 centimeters",
            "lift the arm 20 centimeters upward",
            "move the arm up by 20 centimeters",
            "raise the arm up by twenty centimeters",
            "lift the arm twenty centimeters upward",
            "move the arm up by twenty centimeters",
            "raise arm up a lot",
            "raise the arm up a lot",
            "lift the arm up a lot",
            "move the arm upward a lot",
            "raise the arm significantly",
            "lift the arm up a great deal",
            "move the arm up a large distance",
            "raise the arm up extensively",
            "lift the arm up substantially",
            "move the arm far upward",
            "raise the arm up by a large amount",
            "lift the arm a considerable distance upward",
            "move the arm up considerably",
            "raise the arm up to a great extent",
            "lift the arm far upward",
            "move the arm up by a considerable margin",
            "raise the arm up a long way",
            "lift the arm upward by a significant amount"
        ],
        "3_0": [
            "roll arm counterclockwise a lot",
            "roll arm counterclockwise significantly",
            "roll arm 90 degrees counterclockwise",
            "roll arm ninety degrees counterclockwise",
            "roll arm 90 degrees counterclockwise",
        ],
        "3_1": [
            "roll arm 45 degrees counterclockwise",
            "roll arm fourty five degrees counterclockwise",
            "roll arm counterclockwise",
        ],
        "3_2": [
            "roll arm counterclockwise a bit",
            "roll arm counterclockwise slightly",
            "roll arm fifteen degrees counterclockwise",
            "roll arm 15 degrees counterclockwise",
        ],
        "3_3": [
            "roll arm counterclockwise a tiny bit",
            "roll arm counterclockwise very slightly",
            "roll arm 5 degrees counterclockwise",
            "roll arm five degrees counterclockwise",
        ],
        "3_4": [
            "roll arm clockwise a tiny bit",
            "roll arm clockwise very slightly",
            "roll arm 5 degrees clockwise",
            "roll arm five degrees clockwise",
        ],
        "3_5": [
            "roll arm clockwise a bit",
            "roll arm clockwise slightly",
            "roll arm 15 degrees clockwise",
            "roll arm fifteen degrees clockwise",
        ],
        "3_6": [
            "roll arm 45 degrees clockwise",
            "roll arm fourty five degrees clockwise",
            "roll arm clockwise",
        ],
        "3_7": [
            "roll arm clockwise a lot",
            "roll arm clockwise significantly",
            "roll arm 90 degrees clockwise",
            "roll arm ninety degrees clockwise",
            "roll arm 90 degrees clockwise",
        ],
        "4_0": [
            "tilt arm up a lot",
            "tilt arm up significantly",
            "tilt arm up 90 degrees",
            "tilt arm up ninety degrees",
        ], 
        "4_1": [
            "tilt arm up 45 degrees",
            "tilt arm up fourty five degrees",
            "tilt arm up",
        ],
        "4_2": [
            "tilt arm up a bit",
            "tilt arm up slightly",
            "tilt arm up 15 degrees",
            "tilt arm up fifteen degrees",
        ],
        "4_3": [
            "tilt arm up a tiny bit",
            "tilt arm up very slightly",
            "tilt arm up 5 degrees",
            "tilt arm up five degrees",
        ],
        "4_4": [
            "tilt arm down a tiny bit",
            "tilt arm down very slightly",
            "tilt arm down 5 degrees",
            "tilt arm down five degrees",
        ],
        "4_5": [
            "tilt arm down a bit",
            "tilt arm down slightly",
            "tilt arm down 15 degrees",
            "tilt arm down fifteen degrees",
        ],
        "4_6": [
            "tilt arm down 45 degrees",
            "tilt arm down fourty five degrees",
            "tilt down 45 degrees",
            "tilt arm down",
        ],
        "4_7": [
            "tilt arm down a lot",
            "tilt arm down significantly",
            "tilt arm down 90 degrees",
            "tilt arm down ninety degrees",
        ],
        "5_0": [
            "yaw arm counterclockwise a lot",
            "yaw arm counterclockwise significantly",
            "yaw arm 90 degrees counterclockwise",
            "yaw arm ninety degrees counterclockwise",
            "yaw arm 90 degrees counterclockwise",
        ],
        "5_1": [
            "yaw arm 45 degrees counterclockwise",
            "yaw arm fourty five degrees counterclockwise",
            "yaw arm counterclockwise",
        ],
        "5_2": [
            "yaw arm counterclockwise a bit",
            "yaw arm counterclockwise slightly",
            "yaw arm fifteen degrees counterclockwise",
            "yaw arm 15 degrees counterclockwise",
        ], 
        "5_3": [
            "yaw arm counterclockwise a tiny bit",
            "yaw arm counterclockwise very slightly",
            "yaw arm 5 degrees counterclockwise",
            "yaw arm five degrees counterclockwise",
        ], 
        "5_4": [
            "yaw arm clockwise a tiny bit",
            "yaw arm clockwise very slightly",
            "yaw arm 5 degrees clockwise",
            "yaw arm five degrees clockwise",
        ],
        "5_5": [
            "yaw arm clockwise a bit",
            "yaw arm clockwise slightly",
            "yaw arm 15 degrees clockwise",
            "yaw arm fifteen degrees clockwise",
        ],
        "5_6": [
            "yaw arm 45 degrees clockwise",
            "yaw arm fourty five degrees clockwise",
            "yaw arm clockwise",
        ],
        "5_7": [
            "yaw arm clockwise a lot",
            "yaw arm clockwise significantly",
            "yaw arm 90 degrees clockwise",
            "yaw arm ninety degrees clockwise",
            "yaw arm 90 degrees clockwise",
        ],
    },
    "gripper": {
        "0_0": "close the gripper",   
        "0_1": "open the gripper"
    }
}


if __name__ == '__main__':


    ee = NATURAL_LANGUAGE_SUPERVISION['end_effector']
    s = 0
    for key, val in ee.items():
        s += len(val)
    print(s)


